[package]
name = "geode-finder"
version = "2.2.0"
edition = "2024"
description = "Tool to search for geodes and budding amethyst clusters in a Minecraft world"
repository = "https://github.com/soulsoiledit/geode-finder"
license = "MIT"
keywords = ["minecraft", "amethyst", "geode", "finder", "search"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
indicatif = "0.18.6"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
